.job_template: &cabal_build
  stage: build
  script:
    - cabal update
    - cabal install --prefix $CI_PROJECT_DIR/.cabal --only-dependencies
    - cabal configure --prefix $CI_PROJECT_DIR/.cabal
    - cabal build

.job_template: &cabal_cache
  paths:
    - .cabal

stages:
  - build
  - test
    #  - deploy

GHC 7.10:
  <<: *cabal_build
  image: haskell:7.10
  cache:
    <<: *cabal_cache
    key: ghc-7.10

GHC 8.0:
  <<: *cabal_build
  image: haskell:8.0
  cache:
    <<: *cabal_cache
    key: ghc-8.0

GHC 8.2:
  <<: *cabal_build
  before_script:
    - cabal update
    - cabal install alex happy
  image: haskell:8.2
  cache:
    <<: *cabal_cache
    key: ghc-8.2

Integration tests:
  image: fpco/stack-build:lts-11
  services:
    - name: eventstore/eventstore:release-4.1.0
      alias: eventstore
  script:
    - stack --stack-root $CI_PROJECT_DIR/stack_root test --fast
  cache:
    key: stack
    paths:
      - stack_root

# push on hackage:
#   stage: deploy
#   when: manual
