.job_template: &cabal_build
  stage: build
  script:
    - cabal update
    - ghc-pkg init $CI_PROJECT_DIR/pkg-db || true
    - cabal install --package-db $CI_PROJECT_DIR/pkg-db --prefix $CI_PROJECT_DIR/ci-cabal --only-dependencies
    - cabal configure --package-db $CI_PROJECT_DIR/pkg-db --prefix $CI_PROJECT_DIR/ci-cabal
    - cabal build
    - cabal sdist

.job_template: &cabal_cache
  paths:
    - pkg-db
    - ci-cabal

stages:
  - build
  - test
  - deploy
  - publish

GHC 7.10:
  <<: *cabal_build
  image: haskell:7.10
  cache:
    <<: *cabal_cache
    key: ghc-7.10

GHC 8.0:
  <<: *cabal_build
  image: haskell:8.0
  cache:
    <<: *cabal_cache
    key: ghc-8.0

GHC 8.2:
  <<: *cabal_build
  before_script:
    - cabal update
    - cabal install alex happy
  image: haskell:8.2
  cache:
    <<: *cabal_cache
    key: ghc-8.2

GHC 8.4:
  <<: *cabal_build
  before_script:
    - cabal update
    - cabal install alex happy
  image: haskell:8.4
  cache:
    <<: *cabal_cache
    key: ghc-8.4
  artifacts:
    paths:
      - dist/

Integration tests:
  image: fpco/stack-build:lts-11
  variables:
    EVENTSTORE_HOST: "eventstore"
  services:
    - name: eventstore/eventstore:release-4.1.0
      alias: eventstore
  script:
    - stack --stack-root $CI_PROJECT_DIR/stack_root test --fast
  cache:
    key: stack
    paths:
      - stack_root

Upload on hackage:
  stage: deploy
  script:
    - apt update
    - apt install -y curl
    - cabal upload --username=$HACKAGE_LOGIN --password=$HACKAGE_PASSWORD $(ls dist/eventstore*)
  image: haskell:8.4
  dependencies:
    - GHC 8.4
  when: manual

Publish on hackage:
  stage: publish
  script:
    - apt update
    - apt install -y curl
    - cabal upload --username=$HACKAGE_LOGIN --password=$HACKAGE_PASSWORD --publish $(ls dist/eventstore*)
  image: haskell:8.4
  when: manual
  dependencies:
    - GHC 8.4

