.job_template: &cabal_build
  stage: build
  script:
    - curl -G -L -o artifacts.zip --data-urlencode "job=${CI_JOB_NAME}" $ARTIFACTS_URL || true
    - unzip -q artifacts.zip || true
    - cabal update
    - ghc-pkg init $CI_PROJECT_DIR/pkg-db || true
    - cabal install --package-db $CI_PROJECT_DIR/pkg-db --prefix $CI_PROJECT_DIR/ci-cabal --only-dependencies
    - cabal configure --package-db $CI_PROJECT_DIR/pkg-db --prefix $CI_PROJECT_DIR/ci-cabal
    - cabal build
    - cabal sdist
  artifacts:
    paths:
      - dist/
      - pkg-db/
      - ci-cabal/

.job_template: &cabal_cache
  paths:
    - pkg-db
    - ci-cabal

variables:
  ARTIFACTS_URL: "${CI_PROJECT_URL}/-/jobs/artifacts/dev/1.0/download"

before_script:
  - apt update && apt install -y unzip curl

stages:
  - build
  - test
  - deploy
  - publish

GHC 7.10:
  <<: *cabal_build
  image: haskell:7.10

GHC 8.0:
  <<: *cabal_build
  image: haskell:8.0

GHC 8.2:
  <<: *cabal_build
  before_script:
    - apt update && apt install -y unzip curl
    - cabal update
    - cabal install alex happy
  image: haskell:8.2

GHC 8.4:
  <<: *cabal_build
  before_script:
    - apt update && apt install -y unzip curl
    - cabal update
    - cabal install alex happy
  image: haskell:8.4

GHC 8.6:
  image: haskell:8.6
  stage: build
  before_script:
    - apt update && apt install -y unzip curl
    - cabal new-update
    - cabal new-install alex happy
  script:
    - curl -G -L -o artifacts.zip --data-urlencode "job=${CI_JOB_NAME}" $ARTIFACTS_URL || true
    - unzip -q artifacts.zip || true
    - cabal --store-dir $CI_PROJECT_DIR/ci-cabal new-configure
    - cabal --store-dir $CI_PROJECT_DIR/ci-cabal new-build
    - cabal new-sdist
  artifacts:
    paths:
      - dist-newstyle/
      - ci-cabal/

Integration tests:
  image: haskell:8.6
  variables:
    EVENTSTORE_HOST: "eventstore"
  services:
    - name: eventstore/eventstore:release-4.1.0
      alias: eventstore

  script:
    - cabal new-update
    - cabal --store-dir $CI_PROJECT_DIR/ci-cabal new-test
  dependencies:
    - GHC 8.6

Upload on hackage:
  stage: deploy
  script:
    - apt update
    - apt install -y curl
    - cabal upload --username=$HACKAGE_LOGIN --password=$HACKAGE_PASSWORD $(ls dist-newstyle/sdist/eventstore*)
  image: haskell:8.6
  dependencies:
    - GHC 8.6
  when: manual

Publish on hackage:
  stage: publish
  script:
    - apt update
    - apt install -y curl
    - cabal upload --username=$HACKAGE_LOGIN --password=$HACKAGE_PASSWORD --publish $(ls dist-newstyle/sdist/eventstore*)
  image: haskell:8.6
  when: manual
  dependencies:
    - GHC 8.6

