version: 2
jobs:
  stack:
    docker:
      - image: yoeight/eventstore-lib-dev:latest

    steps:
      - checkout

      - restore_cache:
          key: eventstore-stack{{ checksum "package.yaml" }}

      - run:
          name: Stack with GHC 8.2
          command: stack build --fast --pedantic

      - save_cache:
          paths:
            - /root/.stack

          key: eventstore-stack{{ checksum "package.yaml" }}

  ghc-8.2:
    docker:
      - image: haskell:8.2

    steps:
      - checkout

      - restore_cache:
          key: eventstore-8.2-3{{ checksum "package.yaml" }}

      - run:
          name: GHC 8.2.1
          command: |
            cabal update
            cabal install --only-dependencies
            cabal configure
            cabal install

      - save_cache:
          paths:
            - /root/.cabal

          key: eventstore-8.2-3{{ checksum "package.yaml" }}

  ghc-8.0:
    docker:
      - image: haskell:8.0

    steps:
      - checkout

      - restore_cache:
          key: eventstore-8.0-2{{ checksum "package.yaml" }}

      - run:
          name: GHC 8.0.2
          command: |
            cabal update
            cabal install --only-dependencies
            cabal configure
            cabal install

      - save_cache:
          paths:
            - /root/.cabal

          key: eventstore-8.0-2{{ checksum "package.yaml" }}

  ghc-7.10:
    docker:
      - image: haskell:7.10

    steps:
      - checkout

      - restore_cache:
          key: eventstore-7.10-{{ checksum "package.yaml" }}

      - run:
          name: GHC 7.10
          command: |
            cabal update
            cabal install --only-dependencies
            cabal configure
            cabal install

      - save_cache:
          paths:
            - /root/.cabal

          key: eventstore-7.10-{{ checksum "package.yaml" }}

  # This build is disable till 'monad-logger' package got fixed.
  #
  # ghc-7.8:
  #   docker:
  #     - image: haskell:7.8

  #   steps:
  #     - checkout

  #     - restore_cache:
  #         key: eventstore-7.8-{{ checksum "package.yaml" }}

  #     - run:
  #         name: GHC 7.8
  #         command: |
  #           cabal update
  #           cabal install --only-dependencies
  #           cabal configure
  #           cabal install

  #     - save_cache:
  #         paths:
  #           - /root/.cabal

  #         key: eventstore-7.8-{{ checksum "package.yaml" }}

  tests:
    docker:
      - image: yoeight/eventstore-lib-dev:latest
      - image: eventstore/eventstore:release-4.0.3

    steps:
      - checkout

      - restore_cache:
          key: eventstore-stack{{ checksum "package.yaml" }}

      - run:
          name: Tests
          command: stack test

      - save_cache:
          paths:
            - /root/.stack

          key: eventstore-stack{{ checksum "package.yaml" }}

workflows:
  version: 2
  build-test:
    jobs:
      - stack
      - ghc-8.2
      - ghc-8.0
      - ghc-7.10
      # - ghc-7.8

      - tests:
          requires:
            - stack

