name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: haskell:8.10

    services:
      eventstore:
        image: eventstore/eventstore:release-5.0.11
        ports:
          - 1113/tcp

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        cabal --version
        cabal new-update
    - name: Build
      env:
        EVENTSTORE_HOST: eventstore
      run: |
        cabal new-test
